//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.07 at 02:48:05 PM CEST 
//


package it.rve.protocollo.xsd.richiesta_protocollazione;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Riferimento" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numero_protocollo" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="data_protocollo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "riferimento"
})
@XmlRootElement(name = "Riferimenti")
public class Riferimenti {

    @XmlElement(name = "Riferimento", required = true)
    protected List<Riferimenti.Riferimento> riferimento;

    /**
     * Gets the value of the riferimento property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the riferimento property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRiferimento().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Riferimenti.Riferimento }
     * 
     * 
     */
    public List<Riferimenti.Riferimento> getRiferimento() {
        if (riferimento == null) {
            riferimento = new ArrayList<Riferimenti.Riferimento>();
        }
        return this.riferimento;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numero_protocollo" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="data_protocollo" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numeroProtocollo",
        "dataProtocollo"
    })
    public static class Riferimento {

        @XmlElement(name = "numero_protocollo", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger numeroProtocollo;
        @XmlElement(name = "data_protocollo", required = true, type = String.class)
        @XmlJavaTypeAdapter(Adapter2 .class)
        @XmlSchemaType(name = "date")
        protected Calendar dataProtocollo;

        /**
         * Gets the value of the numeroProtocollo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumeroProtocollo() {
            return numeroProtocollo;
        }

        /**
         * Sets the value of the numeroProtocollo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumeroProtocollo(BigInteger value) {
            this.numeroProtocollo = value;
        }

        /**
         * Gets the value of the dataProtocollo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Calendar getDataProtocollo() {
            return dataProtocollo;
        }

        /**
         * Sets the value of the dataProtocollo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataProtocollo(Calendar value) {
            this.dataProtocollo = value;
        }

    }

}
