
package it.rve.protocollo.lapiswebsoap;

import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LapisWebSOAPService", targetNamespace = "http://localhost/LapisWebSOAP", wsdlLocation = "classpath:LapisWebSoap.wsdl")
public class LapisWebSOAPService
    extends Service
{

    private final static URL LAPISWEBSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.rve.protocollo.lapiswebsoap.LapisWebSOAPService.class.getName());

    static {
    	URL url = it.rve.protocollo.lapiswebsoap.LapisWebSOAPService.class.getResource("LapisWebSoap.wsdl");
        LAPISWEBSOAPSERVICE_WSDL_LOCATION = url;
    }

    public LapisWebSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LapisWebSOAPService() {
        super(LAPISWEBSOAPSERVICE_WSDL_LOCATION, new QName("http://localhost/LapisWebSOAP", "LapisWebSOAPService"));
    }

    /**
     * 
     * @return
     *     returns LapisWebSOAPType
     */
    @WebEndpoint(name = "LapisWebSOAPPort")
    public LapisWebSOAPType getLapisWebSOAPPort() {
        return super.getPort(new QName("http://localhost/LapisWebSOAP", "LapisWebSOAPPort"), LapisWebSOAPType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LapisWebSOAPType
     */
    @WebEndpoint(name = "LapisWebSOAPPort")
    public LapisWebSOAPType getLapisWebSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/LapisWebSOAP", "LapisWebSOAPPort"), LapisWebSOAPType.class, features);
    }

}
