
package it.rve.protocollo.lapiswebsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LapisWebSOAPType", targetNamespace = "http://localhost/LapisWebSOAP")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LapisWebSOAPType {


    /**
     * 
     * @param xml
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "LapisWebSOAP", action = "urn:#LapisWebSOAP")
    @WebResult(name = "LapisWebSOAPReturn", partName = "LapisWebSOAPReturn")
    public boolean lapisWebSOAP(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Validatore", action = "urn:#Validatore")
    @WebResult(name = "ValidatoreReturn", partName = "ValidatoreReturn")
    public String validatore(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProtoBatch", action = "urn:#ProtoBatch")
    @WebResult(name = "ProtoBatchReturn", partName = "ProtoBatchReturn")
    public String protoBatch(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param codice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProtoBatchLog", action = "urn:#ProtoBatchLog")
    @WebResult(name = "ProtoBatchLogReturn", partName = "ProtoBatchLogReturn")
    public String protoBatchLog(
        @WebParam(name = "codice", partName = "codice")
        String codice);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PBrotoBatch", action = "urn:#PBrotoBatch")
    @WebResult(name = "PBrotoBatchReturn", partName = "PBrotoBatchReturn")
    public String pBrotoBatch(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param codice
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PBrotoBatchLog", action = "urn:#PBrotoBatchLog")
    @WebResult(name = "PBrotoBatchLogReturn", partName = "PBrotoBatchLogReturn")
    public String pBrotoBatchLog(
        @WebParam(name = "codice", partName = "codice")
        String codice);

    /**
     * 
     * @param xml
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ProtocollaArrivo", action = "urn:#ProtocollaArrivo")
    @WebResult(name = "ProtocollaArrivoReturn", partName = "ProtocollaArrivoReturn")
    public String protocollaArrivo(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ModificaStruttura", action = "urn:#ModificaStruttura")
    @WebResult(name = "ModificaStrutturaReturn", partName = "ModificaStrutturaReturn")
    public boolean modificaStruttura(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param xml
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AggiungiRicevuta", action = "urn:#AggiungiRicevuta")
    @WebResult(name = "AggiungiRicevutaReturn", partName = "AggiungiRicevutaReturn")
    public boolean aggiungiRicevuta(
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getProfile")
    @WebResult(name = "getProfileReturn", partName = "getProfileReturn")
    public String getProfile(
        @WebParam(name = "account", partName = "account")
        String account);

    /**
     * 
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getPermission")
    @WebResult(name = "getPermissionReturn", partName = "getPermissionReturn")
    public String getPermission(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura);

    /**
     * 
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getOwner")
    @WebResult(name = "getOwnerReturn", partName = "getOwnerReturn")
    public String getOwner(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura);

    /**
     * 
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getIDC")
    @WebResult(name = "getIDCReturn", partName = "getIDCReturn")
    public String getIDC(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura);

    /**
     * 
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getFather")
    @WebResult(name = "getFatherReturn", partName = "getFatherReturn")
    public String getFather(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura);

    /**
     * 
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getMovimentazione")
    @WebResult(name = "getMovimentazioneReturn", partName = "getMovimentazioneReturn")
    public String getMovimentazione(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura);

    /**
     * 
     * @param dataFine
     * @param dataInizio
     * @param struttura
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getFatture")
    @WebResult(name = "getFattureReturn", partName = "getFattureReturn")
    public String getFatture(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura,
        @WebParam(name = "data_inizio", partName = "data_inizio")
        String dataInizio,
        @WebParam(name = "data_fine", partName = "data_fine")
        String dataFine);

    /**
     * 
     * @param numeroProto
     * @param struttura
     * @param dataProto
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getDettaglioFattura")
    @WebResult(name = "getDettaglioFatturaReturn", partName = "getDettaglioFatturaReturn")
    public String getDettaglioFattura(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura,
        @WebParam(name = "numero_proto", partName = "numero_proto")
        String numeroProto,
        @WebParam(name = "data_proto", partName = "data_proto")
        String dataProto);

    /**
     * 
     * @param codApplicativo
     * @param numeroProto
     * @param struttura
     * @param dataProto
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getStatoSpedizione")
    @WebResult(name = "getStatoSpedizioneReturn", partName = "getStatoSpedizioneReturn")
    public String getStatoSpedizione(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura,
        @WebParam(name = "numero_proto", partName = "numero_proto")
        String numeroProto,
        @WebParam(name = "data_proto", partName = "data_proto")
        String dataProto,
        @WebParam(name = "cod_applicativo", partName = "cod_applicativo")
        String codApplicativo);

    /**
     * 
     * @param operatore
     * @param ieFascicolo
     * @param numeroProto
     * @param struttura
     * @param masCod
     * @param dataProto
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:#insertFolder")
    @WebResult(name = "insertFolderReturn", partName = "insertFolderReturn")
    public boolean insertFolder(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura,
        @WebParam(name = "numero_proto", partName = "numero_proto")
        String numeroProto,
        @WebParam(name = "data_proto", partName = "data_proto")
        String dataProto,
        @WebParam(name = "mas_cod", partName = "mas_cod")
        String masCod,
        @WebParam(name = "ie_fascicolo", partName = "ie_fascicolo")
        String ieFascicolo,
        @WebParam(name = "operatore", partName = "operatore")
        String operatore);

    /**
     * 
     * @param operatore
     * @param ieFascicolo
     * @param numeroProto
     * @param struttura
     * @param masCod
     * @param dataProto
     * @return
     *     returns boolean
     */
    @WebMethod(action = "urn:#deleteFolder")
    @WebResult(name = "deleteFolderReturn", partName = "deleteFolderReturn")
    public boolean deleteFolder(
        @WebParam(name = "struttura", partName = "struttura")
        String struttura,
        @WebParam(name = "numero_proto", partName = "numero_proto")
        String numeroProto,
        @WebParam(name = "data_proto", partName = "data_proto")
        String dataProto,
        @WebParam(name = "mas_cod", partName = "mas_cod")
        String masCod,
        @WebParam(name = "ie_fascicolo", partName = "ie_fascicolo")
        String ieFascicolo,
        @WebParam(name = "operatore", partName = "operatore")
        String operatore);

    /**
     * 
     * @param fileId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:#getPEC")
    @WebResult(name = "getPECReturn", partName = "getPECReturn")
    public String getPEC(
        @WebParam(name = "fileId", partName = "fileId")
        String fileId);

}
