//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.18 at 06:09:02 PM CEST 
//


package it.veneto.regione.firma;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _METADATA_QNAME = new QName("", "METADATA");
    private final static QName _INFORMAZIONI_QNAME = new QName("", "INFORMAZIONI");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIRMAFILES }
     * 
     */
    public FIRMAFILES createFIRMAFILES() {
        return new FIRMAFILES();
    }

    /**
     * Create an instance of {@link FILE }
     * 
     */
    public FILE createFILE() {
        return new FILE();
    }

    /**
     * Create an instance of {@link DOCUMENTS }
     * 
     */
    public DOCUMENTS createDOCUMENTS() {
        return new DOCUMENTS();
    }

    /**
     * Create an instance of {@link DOCUMENT }
     * 
     */
    public DOCUMENT createDOCUMENT() {
        return new DOCUMENT();
    }

    /**
     * Create an instance of {@link SOURCE }
     * 
     */
    public SOURCE createSOURCE() {
        return new SOURCE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "METADATA")
    public JAXBElement<String> createMETADATA(String value) {
        return new JAXBElement<String>(_METADATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INFORMAZIONI")
    public JAXBElement<String> createINFORMAZIONI(String value) {
        return new JAXBElement<String>(_INFORMAZIONI_QNAME, String.class, null, value);
    }

}
