
package it.veneto.regione.pagamenti.ente.pagamentitelematicidovutipagati;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PagamentiTelematiciDovutiPagatiService", targetNamespace = "http://www.regione.veneto.it/pagamenti/ente/PagamentiTelematiciDovutiPagati", wsdlLocation = "file:/D:/workspaces/ECM/IntegrazioniECM/src/pa-per-ente.wsdl")
public class PagamentiTelematiciDovutiPagatiService
    extends Service
{

    private final static URL PAGAMENTITELEMATICIDOVUTIPAGATISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.veneto.regione.pagamenti.ente.pagamentitelematicidovutipagati.PagamentiTelematiciDovutiPagatiService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.veneto.regione.pagamenti.ente.pagamentitelematicidovutipagati.PagamentiTelematiciDovutiPagatiService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/workspaces/ECM/IntegrazioniECM/src/pa-per-ente.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/workspaces/ECM/IntegrazioniECM/src/pa-per-ente.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGAMENTITELEMATICIDOVUTIPAGATISERVICE_WSDL_LOCATION = url;
    }

    public PagamentiTelematiciDovutiPagatiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagamentiTelematiciDovutiPagatiService() {
        super(PAGAMENTITELEMATICIDOVUTIPAGATISERVICE_WSDL_LOCATION, new QName("http://www.regione.veneto.it/pagamenti/ente/PagamentiTelematiciDovutiPagati", "PagamentiTelematiciDovutiPagatiService"));
    }

    /**
     * 
     * @return
     *     returns PagamentiTelematiciDovutiPagati
     */
    @WebEndpoint(name = "PagamentiTelematiciDovutiPagatiPort")
    public PagamentiTelematiciDovutiPagati getPagamentiTelematiciDovutiPagatiPort() {
        return super.getPort(new QName("http://www.regione.veneto.it/pagamenti/ente/PagamentiTelematiciDovutiPagati", "PagamentiTelematiciDovutiPagatiPort"), PagamentiTelematiciDovutiPagati.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagamentiTelematiciDovutiPagati
     */
    @WebEndpoint(name = "PagamentiTelematiciDovutiPagatiPort")
    public PagamentiTelematiciDovutiPagati getPagamentiTelematiciDovutiPagatiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.regione.veneto.it/pagamenti/ente/PagamentiTelematiciDovutiPagati", "PagamentiTelematiciDovutiPagatiPort"), PagamentiTelematiciDovutiPagati.class, features);
    }

}
