package it.tredi.ecm.dao.enumlist;

public enum AlertTipoEnum {
	SCADENZA_ACCREDITAMENTO_PROVVISORIO,//UNO PER ACCREDITAMENTO PROVVISORIO
	SCADENZA_ACCREDITAMENTO_STANDARD,//UNO PER ACCREDITAMENTO STANDARD
	SCADENZA_QUOTA_ANNUALE,//UNO PER OGNI QUOTA ANNUALE
	SCADENZA_COMPILAZIONE_PFA,//UNO OGNI ANNO
	SCADENZA_RELAZIONE_ANNUALE,//UNO OGNI ANNO
	SCADENZA_PAGAMENTO_E_RENDICONTAZIONE_EVENTO,//PER OGNI EVENTO
	SCADENZA_COMPILAZIONE_DOMANDA_ACCREDITAMENTO_STANDARD;//UNO PER PROVIDER
}
