package it.tredi.ecm.dao.enumlist;

public enum ProfileEnum {
	PROVIDER,
	PROVIDERUSERADMIN,
	PROVIDER_VISUALIZZATORE,
	ADMIN,
	SEGRETERIA,
	RESPONSABILE_SEGRETERIA_ECM,
	REFEREE,
	COMMISSIONE,
	ENGINEERING,
	COMPONENTE_OSSERVATORIO,
	REFERENTE_INFORMATICO;
}
