package it.tredi.ecm.dao.enumlist;

public enum ProfileEnum {
	PROVIDER,
	PROVIDERUSERADMIN,
	PROVIDER_VISUALIZZATORE,
	PROVIDER_ACCOUNT_COMUNICAZIONI,
	ADMIN,
	SEGRETERIA,
	SEGRETERIA_ACCOUNT_COMUNICAZIONI,
	RESPONSABILE_SEGRETERIA_ECM,
	REFEREE,
	COMMISSIONE,
	ENGINEERING,
	COMPONENTE_OSSERVATORIO,
	REFERENTE_INFORMATICO;
}
