package it.tredi.ecm.dao.enumlist;

import lombok.Getter;

@Getter
public enum RoleEnum {
	PROVIDER_SHOW, PROVIDER_SHOW_ALL, 
	PROVIDER_EDIT, PROVIDER_EDIT_ALL, 
	ACCREDITAMENTO_SHOW, ACCREDITAMENTO_SHOW_ALL, 
	ACCREDITAMENTO_EDIT, ACCREDITAMENTO_EDIT_ALL, 
	PERSONA_EDIT, PERSONA_EDIT_ALL, 
	PERSONA_SHOW, PERSONA_SHOW_ALL,
	USER_SHOW, USER_SHOW_ALL,
	USER_EDIT, USER_EDIT_ALL,
	USER_CREATE;
}
