
package it.peng.wr.webservice.protocollo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Protocol", targetNamespace = "http://protocollo.webservice.wr.peng.it/", wsdlLocation = "http://172.18.11.30/WebRainbow/Protocol?wsdl")
public class Protocol
    extends Service
{

    private final static URL PROTOCOL_WSDL_LOCATION;
    private final static WebServiceException PROTOCOL_EXCEPTION;
    private final static QName PROTOCOL_QNAME = new QName("http://protocollo.webservice.wr.peng.it/", "Protocol");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.18.11.30/WebRainbow/Protocol?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROTOCOL_WSDL_LOCATION = url;
        PROTOCOL_EXCEPTION = e;
    }

    public Protocol() {
        super(__getWsdlLocation(), PROTOCOL_QNAME);
    }

    public Protocol(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROTOCOL_QNAME, features);
    }

    public Protocol(URL wsdlLocation) {
        super(wsdlLocation, PROTOCOL_QNAME);
    }

    public Protocol(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROTOCOL_QNAME, features);
    }

    public Protocol(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Protocol(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProtocolWebService
     */
    @WebEndpoint(name = "ProtocolWebServicePort")
    public ProtocolWebService getProtocolWebServicePort() {
        return super.getPort(new QName("http://protocollo.webservice.wr.peng.it/", "ProtocolWebServicePort"), ProtocolWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProtocolWebService
     */
    @WebEndpoint(name = "ProtocolWebServicePort")
    public ProtocolWebService getProtocolWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://protocollo.webservice.wr.peng.it/", "ProtocolWebServicePort"), ProtocolWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROTOCOL_EXCEPTION!= null) {
            throw PROTOCOL_EXCEPTION;
        }
        return PROTOCOL_WSDL_LOCATION;
    }

}
