SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = ecmdb, pg_catalog;

UPDATE ecmdb.obiettivo SET nome='Non rientra in uno degli obiettivi regionali (1)' WHERE id=1024;
UPDATE ecmdb.obiettivo SET nome='Appropriatezza delle prestazioni sanitarie in conformità ai LEA (2)' WHERE id=1025;
UPDATE ecmdb.obiettivo SET nome='Governo clinico, qualità e sicurezza del paziente (3)' WHERE id=1026;
UPDATE ecmdb.obiettivo SET nome='Adozione di linee guida basate sull’evidenza, qualità dei sistemi e dei processi clinico assistenziali (4)' WHERE id=1027;
UPDATE ecmdb.obiettivo SET nome='Umanizzazione delle cure/relazione/comunicazione (5)' WHERE id=1028;
UPDATE ecmdb.obiettivo SET nome='Cure palliative e terapia del dolore (6)' WHERE id=1029;
UPDATE ecmdb.obiettivo SET nome='Prevenzione e presa in carico della persona affetta da cronicità (7)' WHERE id=1030;
UPDATE ecmdb.obiettivo SET nome='Integrazione professionale tra ospedale e territorio, con sviluppo e implementazione dei PDTA (prioritariamente su BPCO, scompenso cardiaco, fibrillazione atriale, diabete, sclerosi multipla) (8)' WHERE id=1031;
UPDATE ecmdb.obiettivo SET nome='Malattia di Alzheimer e altri tipi di declino cognitivo e demenze (9)' WHERE id=1032;
UPDATE ecmdb.obiettivo SET nome='Promozione corretti stili di vita (10)' WHERE id=1033;
UPDATE ecmdb.obiettivo SET nome='Promozione dell’appropriatezza prescrittiva dei farmaci (11)' WHERE id=1034;
UPDATE ecmdb.obiettivo SET nome='Interventi socio-sanitari (famiglia, infanzia, adolescenza, giovani, anziani, disabilità, dipendenze, salute mentale) (12)' WHERE id=1035;
UPDATE ecmdb.obiettivo SET nome='Cultura del lavoro in team multiprofessionale e adozioni di modelli di lavoro in rete (13)' WHERE id=1036;
UPDATE ecmdb.obiettivo SET nome='Sicurezza degli operatori nell''ambiente di lavoro (T.U. 81/2008) (14)' WHERE id=1037;
UPDATE ecmdb.obiettivo SET nome='Valorizzazione delle risorse umane (15)' WHERE id=1038;
UPDATE ecmdb.obiettivo SET nome='Epidemiologia- prevenzione e promozione della salute. (10)' WHERE id=1039;
UPDATE ecmdb.obiettivo SET nome='Argomenti di carattere generale: informatica e lingua inglese scientifica di livello avanzato. (17)' WHERE id=1040;
UPDATE ecmdb.obiettivo SET nome='Contenuti tecnico-professionali (conoscenze e competenze) specifici di ciascuna professione, di ciascuna specializzazione e di ciascuna attivita ultraspecialistica. malattie rare. (18)' WHERE id=1041;
UPDATE ecmdb.obiettivo SET nome='Medicine non convenzionali: valutazione dell’efficacia in ragione degli esiti e degli ambiti di complementarieta’. (19)' WHERE id=1042;
UPDATE ecmdb.obiettivo SET nome='Trattamento del dolore acuto e cronico. palliazione. (21)' WHERE id=1043;
UPDATE ecmdb.obiettivo SET nome='Fragilita’ (minori, anziani, tossico-dipendenti. salute mentale): tutela degli aspetti assistenziali e socio-assistenziali. (22)' WHERE id=1044;
UPDATE ecmdb.obiettivo SET nome='Sicurezza alimentare. (23)' WHERE id=1045;
UPDATE ecmdb.obiettivo SET nome='Sicurezza ambientale. (26)' WHERE id=1046;
UPDATE ecmdb.obiettivo SET nome='Sicurezza negli ambienti e nei luoghi di lavoro e patologie correlate.(27)' WHERE id=1047;
UPDATE ecmdb.obiettivo SET nome='Sanita’ veterinaria. (24)' WHERE id=1048;
UPDATE ecmdb.obiettivo SET nome='Farmacoepidemiologia, farmacoeconomia, farmacovigilanza.(25)' WHERE id=1049;
UPDATE ecmdb.obiettivo SET nome='Implementazione della cultura e della sicurezza in materia di donazione - trapianto.(28)' WHERE id=1050;
UPDATE ecmdb.obiettivo SET nome='Innovazione tecnologica: valutazione. miglioramento dei processi di gestione delle tecnologie biomediche e dei dispositivi medici. Health technology assessment.(29)' WHERE id=1051;
UPDATE ecmdb.obiettivo SET nome='Tematiche speciali del SSN e SSR ed a carattere urgente e/o straordinario individuate dalla commissione nazionale ECM e dalle regioni/province autonome per far fronte a specifiche emergenze sanitarie.(20)' WHERE id=1052;
UPDATE ecmdb.obiettivo SET nome='Documentazione clinica, percorsi clinico-assistenziali diagnostici e riabilitativi, profili di assistenza-profili di cura. (3)' WHERE id=1053;
UPDATE ecmdb.obiettivo SET nome='Appropriatezza prestazioni sanitarie nei LEA. Sistemi di valutazione, verifica e miglioramento dell’efficienza e dell’efficacia. (4)' WHERE id=1054;
UPDATE ecmdb.obiettivo SET nome='Integrazione interprofessionale e multiprofessionale, interistituzionale. (8)' WHERE id=1055;
UPDATE ecmdb.obiettivo SET nome='Integrazione fra assistenza territoriale ed ospedaliera. (9)' WHERE id=1056;
UPDATE ecmdb.obiettivo SET nome='Management sanitario. innovazione gestionale e sperimentazione di modelli organizzativi e gestionali. (11)' WHERE id=1057;
UPDATE ecmdb.obiettivo SET nome='Aspetti relazionali (comunicazione interna, esterna, con paziente) e umanizzazione delle cure. (12)' WHERE id=1058;
UPDATE ecmdb.obiettivo SET nome='La comunicazione efficace la privacy ed il consenso informato. (7)' WHERE id=1059;
UPDATE ecmdb.obiettivo SET nome='Metodologia e tecniche di comunicazione sociale per lo sviluppo dei programmi nazionali e regionali di prevenzione primaria. (13)' WHERE id=1060;
UPDATE ecmdb.obiettivo SET nome='Multiculturalita’ e cultura dell’accoglienza nell’attivita’ sanitaria. (15)' WHERE id=1061;
UPDATE ecmdb.obiettivo SET nome='Tematiche speciali del SSN e SSR ed a carattere urgente e/o straordinario individuate dalla commissione nazionale ECM e dalle regioni/province autonome per far fronte a specifiche emergenze sanitarie. (20)' WHERE id=1062;
UPDATE ecmdb.obiettivo SET nome='Applicazione nella pratica quotidiana dei principi e delle prodcedure dell’evidenze based practice (EBM. EBN. EBP). (1)' WHERE id=1063;
UPDATE ecmdb.obiettivo SET nome='Linee guida protocolli-procedure. (2)' WHERE id=1064;
UPDATE ecmdb.obiettivo SET nome='Principi, procedure e strumenti per il governo clinico delle attività sanitarie. (5)' WHERE id=1065;
UPDATE ecmdb.obiettivo SET nome='La sicurezza del paziente. risk management. (6)' WHERE id=1066;
UPDATE ecmdb.obiettivo SET nome='Epidemiologia – prevenzione e promozione della salute. (10)' WHERE id=1067;
UPDATE ecmdb.obiettivo SET nome='Etica, bioetica e deontologia. (16)' WHERE id=1068;
UPDATE ecmdb.obiettivo SET nome='Argomenti di carattere generale: informatica ed inglese scientifico livello avanzato; normativa in materia sanitaria: i principi etici e civili del ssn. (17)' WHERE id=1069;
UPDATE ecmdb.obiettivo SET nome='Tematiche speciali del SSN e SSR ed a carattere urgente e/o straordinario individuate dalla commissione nazionale ECM e dalle regioni/province autonome per far fronte a specifiche emergenze sanitarie. (20)' WHERE id=1070;

